version: "3.9"
services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
  frontend-app:
    build:
      context: ./appearance
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

