name: Development Workflow

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  run_go_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go with its verison number
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: go mod verify

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Build
      run: go build -o build/ -v ./cmd/app/...

    - name: Vet
      run: go vet ./cmd/app/...

    - name: Lint
      run: staticcheck ./cmd/app/...

    - name: Test
      run: go test -v ./cmd/app/tests/...
    
